version: "3"
services:
  chat-home:
    image: devops-hf/chat-home
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
    ports:
      - '80:8080/tcp'
  consul:
    image: consul
    command: [ "agent", "-server", "-ui", "-node=server-1", "-bootstrap-expect=1", "-client=0.0.0.0" ]
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
  nginx:
    image: nginx
    volumes: 
      - nginx.conf:/etc/nginx/nginx.conf
