kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-role-cluster
rules:
- apiGroups:
  - ""
  - "apps"
  - "networking.k8s.io"
  - "autoscaling"
  - "rbac.authorization.k8s.io"
  resources:
  - pods
  - configmaps
  - deployments
  - secrets
  - services
  - ingresses
  - apps
  - horizontalpodautoscalers
  - statefulsets
  - clusterroles
  - rolebindings
  - serviceaccounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-chat
  namespace: chat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-role-cluster
subjects:
- kind: ServiceAccount
  name: ci-jenkins
  namespace: jenkins
