name: 'Chat Service build'

on:
  push:
    branches:
      - chat-service-master

jobs:
  native:
    name: 'Native'
    runs-on: 'ubuntu-latest'
    container: 
      image: 'quay.io/quarkus/centos-quarkus-maven:19.2.1'
    steps:
      - uses: actions/checkout@v1
        with:
          ref: $GIT_REF
      - name: 'Build'
        run: 'mvn package -Pnative -Dnative-image.docker-build=true'
      - name: 'Dockerize'
        run: docker build -f src/main/docker/Dockerfile.native -t output .'
      - name: 'Publish'
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/chat-service:native
          docker tag output $IMAGE_ID
          docker push $IMAGE_ID
  jvm:
    name: 'JVM'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v1
        with: 
          ref: $GIT_REF
      - name: 'Build'
        run: 'mvn package'
      - name: 'Dockerize'
        run: 'docker build src/main/docker/Dockerfile.jvm -t output .'
      - name: 'Publish'
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/chat-service:jvm
          docker tag output $IMAGE_ID
          docker push $IMAGE_ID

