name: Chat Service build

on: [push]

jobs:
  native:
    name: Native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Build & Dockerize
        run: docker build -f src/main/docker/Dockerfile.multistage -t output .

      - name: Publish
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/chat-service:native
          docker tag output $IMAGE_ID
          docker push $IMAGE_ID
  jvm:
    name: JVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1
        with: 
          ref: ${{ github.ref }}

      - name: Build
        run: mvn package

      - name: Dockerize
        run: docker build -f src/main/docker/Dockerfile.jvm -t output .

      - name: Publish
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/chat-service:jvm
          docker tag output $IMAGE_ID
          docker push $IMAGE_ID

