name: Test workflow

on: [push]

jobs:
  test:
    name: 'Test job'
    runs-on: ubuntu-latest
    steps:
      - name: Prints Trigger Info
        run: 'echo Triggered from ${{ github.ref }}, event: ${{ github.event }}'